###load 'shiny' package
if (!require(shiny)) {
  install.packages("shiny")
}
##load 'MetaCycle' package
if (!require(MetaCycle)) {
  install.packages("MetaCycle")
  library(MetaCycle)
}  else  {
  library(MetaCycle)
}

### By default, the file size limit is 5MB. It can be changed by
### setting this option. Here we'll raise limit to 100MB.
options(shiny.maxRequestSize = 100*1024^2)

###set a flag for 'Run' button
runflag <- 0
###uploading file
shinyServer(function(input, output) {
  ## show the input datafile
  output$contents <- renderTable({
    ## input$file1 will be NULL initially. After the user selects and uploads a file, 
    ## it will be a data frame with 'name', 'size', 'type', and 'datapath' columns.
    ## The 'datapath' column will contain the local filenames where the data can be found.
    inFile <- input$file1
    if (is.null(inFile)) {
      return(NULL)
    }
    inputD <-  read.csv(inFile$datapath)
    if ( ncol(inputD) < 2 ) {
      inputD <- read.delim(inFile$datapath)
    } 
    if ( ncol(inputD) >=2  )  {
      return( head(inputD) )
    } else  {
      return(NULL)
    }
  })
  ## show the necessay value during running shiny function
#   output$teptext <- renderText({
#    tepF <- input$outraw
#    return(class(tepF))
#   })
  ## run the meta2d
  datasetInput <- reactive({
    ## Change when the "update" button is pressed
    if ( input$update > runflag) {
      isolate({
        withProgress({
          setProgress(message = "Processing corpus...")
          inFile <- input$file1
          outRawData <- TRUE
          if (input$outraw == "FALSE") 
          {
            outRawData <- FALSE
          }
          timepoints <- input$timept
          if ( (timepoints == "Header") | grepl(",", timepoints) ) 
          {
              if (grepl(",", timepoints)) {
                timepoints <- gsub("\\s+", "", timepoints, perl = TRUE)
                timepoints <- sub("^,", "", timepoints, perl = TRUE)
                timepoints <- sub(",$", "", timepoints, perl = TRUE)
                timepoints <- unlist( strsplit(timepoints, ",", fixed=TRUE) )
                timepoints <- as.numeric(timepoints)
              }  else  {
                timepoints <- "Line1"
              }
              outL <- meta2d(infile = inFile$datapath, filestyle = input$fstyle,
                             timepoints = timepoints, minper = input$minper,
                             maxper = input$maxper, ARSdefaultPer = input$arsper,
                             cycMethod = input$method, combinePvalue = input$cmbPva,
                             outputFile = FALSE, outIntegration = "onlyIntegration",
                             outRawData = outRawData)
              outD <- outL$meta
          }  else  {
            outD <- NULL
          }
          ## this is a patch used to remove the default directory generated by meta2d
          if (file.exists("metaout") ) {
            unlink("metaout", recursive = TRUE)
          }
        })
      })
      runflag <- input$update
      return(outD)
    }  else  {
      return(NULL)
    }
  })
  ## show the result of meta2d
  output$tabout <- renderTable({
    taboutD <- datasetInput()
    head(taboutD)
  })
  ## downloading file
  output$downloadData <- downloadHandler(
    filename = function() { 
      if (input$fstyle == "txt") {
        paste("meta2d", '.txt', sep='') 
      }  else  {
        paste("meta2d", '.csv', sep='') 
      }
    },
    content = function(file) {
      if (input$fstyle == "txt") {
        write.table(datasetInput(), file, quote = FALSE, sep="\t", row.names=FALSE)
      }  else  {
        write.csv(datasetInput(), file, row.names=FALSE)
      }
    }
  )
})
